from typing import Dict, NamedTuple, Optional, Set

from BaseClasses import Item, ItemClassification


class KHBBSItem(Item):
    game: str = "Kingdom Hearts"


class KHBBSItemData(NamedTuple):
    category: str
    sub: str = "None"
    code: Optional[int] = None
    classification: ItemClassification = ItemClassification.filler
    max_quantity: int = 1
    weight: int = 1
    characters: str = "TVA"


def get_items_by_category(category: str, disclude: list) -> Dict[str, KHBBSItemData]:
    item_dict: Dict[str, KHBBSItemData] = {}
    for name, data in item_table.items():
        if data.category == category and all(x not in name for x in disclude):
            item_dict.setdefault(name, data)

    return item_dict

item_table: Dict[str, KHBBSItemData] = {
    "Victory":                KHBBSItemData("Victory",            code = 227_0000000, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Quick Blitz":            KHBBSItemData("Attack Command",     code = 227_0010000, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Blitz":                  KHBBSItemData("Attack Command",     code = 227_0010001, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Magic Hour":             KHBBSItemData("Attack Command",     code = 227_0010002, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Meteor Crash":           KHBBSItemData("Attack Command",     code = 227_0010003, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Sliding Dash":           KHBBSItemData("Attack Command",     code = 227_0010004, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Fire Dash":              KHBBSItemData("Attack Command",     code = 227_0010005, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Dark Haze":              KHBBSItemData("Attack Command",     code = 227_0010006, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Sonic Blade":            KHBBSItemData("Attack Command",     code = 227_0010007, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Chaos Blade":            KHBBSItemData("Attack Command",     code = 227_0010008, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Zantetsuken":            KHBBSItemData("Attack Command",     code = 227_0010009, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Strike Raid":            KHBBSItemData("Attack Command",     code = 227_0010010, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Freeze Raid":            KHBBSItemData("Attack Command",     code = 227_0010011, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Treasure Raid":          KHBBSItemData("Attack Command",     code = 227_0010012, classification = ItemClassification.filler,      characters = " V "                  ),
    "Spark Raid":             KHBBSItemData("Attack Command",     code = 227_0010013, classification = ItemClassification.filler,      characters = " V "                  ),
    "Wind Raid":              KHBBSItemData("Attack Command",     code = 227_0010014, classification = ItemClassification.filler,      characters = " V "                  ),
    "Fire Surge":             KHBBSItemData("Attack Command",     code = 227_0010015, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Barrier Surge":          KHBBSItemData("Attack Command",     code = 227_0010016, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Thunder Surge":          KHBBSItemData("Attack Command",     code = 227_0010017, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Aerial Slam":            KHBBSItemData("Attack Command",     code = 227_0010018, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Ars Solum":              KHBBSItemData("Attack Command",     code = 227_0010019, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Ars Arcanum":            KHBBSItemData("Attack Command",     code = 227_0010020, classification = ItemClassification.filler,      characters = " V "                  ),
    "Time Splicer":           KHBBSItemData("Attack Command",     code = 227_0010021, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Poison Edge":            KHBBSItemData("Attack Command",     code = 227_0010022, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Wishing Edge":           KHBBSItemData("Attack Command",     code = 227_0010023, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Blizzard Edge":          KHBBSItemData("Attack Command",     code = 227_0010024, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Stun Edge":              KHBBSItemData("Attack Command",     code = 227_0010025, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Slot Edge":              KHBBSItemData("Attack Command",     code = 227_0010026, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Fire Strike":            KHBBSItemData("Attack Command",     code = 227_0010027, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Confusion Strike":       KHBBSItemData("Attack Command",     code = 227_0010028, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Blinding Strike":        KHBBSItemData("Attack Command",     code = 227_0010029, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Tornado Strike":         KHBBSItemData("Attack Command",     code = 227_0010030, classification = ItemClassification.filler,      characters = " V "                  ),
    "Brutal Blast":           KHBBSItemData("Attack Command",     code = 227_0010031, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Magnet Spiral":          KHBBSItemData("Attack Command",     code = 227_0010032, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Salvation":              KHBBSItemData("Attack Command",     code = 227_0010033, classification = ItemClassification.filler,      characters = " V "                  ),
    "Wind Cutter":            KHBBSItemData("Attack Command",     code = 227_0010034, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Limit Storm":            KHBBSItemData("Attack Command",     code = 227_0010035, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Collision Magnet":       KHBBSItemData("Attack Command",     code = 227_0010036, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Geo Impact":             KHBBSItemData("Attack Command",     code = 227_0010037, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Sacrifice":              KHBBSItemData("Attack Command",     code = 227_0010038, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Break Time":             KHBBSItemData("Attack Command",     code = 227_0010039, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Fire":                   KHBBSItemData("Magic Command",      code = 227_0010040, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Fira":                   KHBBSItemData("Magic Command",      code = 227_0010041, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Firaga":                 KHBBSItemData("Magic Command",      code = 227_0010042, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Dark Firaga":            KHBBSItemData("Magic Command",      code = 227_0010043, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Fission Firaga":         KHBBSItemData("Magic Command",      code = 227_0010044, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Triple Firaga":          KHBBSItemData("Magic Command",      code = 227_0010045, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Crawling Fire":          KHBBSItemData("Magic Command",      code = 227_0010046, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Blizzard":               KHBBSItemData("Magic Command",      code = 227_0010047, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Blizzara":               KHBBSItemData("Magic Command",      code = 227_0010048, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Blizzaga":               KHBBSItemData("Magic Command",      code = 227_0010049, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Triple Blizzaga":        KHBBSItemData("Magic Command",      code = 227_0010050, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Thunder":                KHBBSItemData("Magic Command",      code = 227_0010051, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Thundara":               KHBBSItemData("Magic Command",      code = 227_0010052, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Thundaga":               KHBBSItemData("Magic Command",      code = 227_0010053, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Thundaga Shot":          KHBBSItemData("Magic Command",      code = 227_0010054, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Cure":                   KHBBSItemData("Magic Command",      code = 227_0010055, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Cura":                   KHBBSItemData("Magic Command",      code = 227_0010056, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Curaga":                 KHBBSItemData("Magic Command",      code = 227_0010057, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Esuna":                  KHBBSItemData("Magic Command",      code = 227_0010058, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Mine Shield":            KHBBSItemData("Magic Command",      code = 227_0010059, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Mine Square":            KHBBSItemData("Magic Command",      code = 227_0010060, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Seeker Mine":            KHBBSItemData("Magic Command",      code = 227_0010061, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Zero Gravity":           KHBBSItemData("Magic Command",      code = 227_0010062, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Zero Gravira":           KHBBSItemData("Magic Command",      code = 227_0010063, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Zero Graviga":           KHBBSItemData("Magic Command",      code = 227_0010064, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Magnet":                 KHBBSItemData("Magic Command",      code = 227_0010065, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Magnera":                KHBBSItemData("Magic Command",      code = 227_0010066, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Magnega":                KHBBSItemData("Magic Command",      code = 227_0010067, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Munny Magnet":           KHBBSItemData("Magic Command",      code = 227_0010068, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Energy Magnet":          KHBBSItemData("Magic Command",      code = 227_0010069, classification = ItemClassification.filler,      characters = "  A"                  ),
    "D-Link Magnet":          KHBBSItemData("Magic Command",      code = 227_0010070, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Aero":                   KHBBSItemData("Magic Command",      code = 227_0010071, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Aerora":                 KHBBSItemData("Magic Command",      code = 227_0010072, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Aeroga":                 KHBBSItemData("Magic Command",      code = 227_0010073, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Warp":                   KHBBSItemData("Magic Command",      code = 227_0010074, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Faith":                  KHBBSItemData("Magic Command",      code = 227_0010075, classification = ItemClassification.filler,      characters = " V "                  ),
    "Deep Freeze":            KHBBSItemData("Magic Command",      code = 227_0010076, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Glacier":                KHBBSItemData("Magic Command",      code = 227_0010077, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Ice Barrage":            KHBBSItemData("Magic Command",      code = 227_0010078, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Firaga Burst":           KHBBSItemData("Magic Command",      code = 227_0010079, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Raging Storm":           KHBBSItemData("Magic Command",      code = 227_0010080, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Mega Flare":             KHBBSItemData("Magic Command",      code = 227_0010081, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Quake":                  KHBBSItemData("Magic Command",      code = 227_0010082, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Tornado":                KHBBSItemData("Magic Command",      code = 227_0010083, classification = ItemClassification.filler,      characters = " V "                  ),
    "Meteor":                 KHBBSItemData("Magic Command",      code = 227_0010084, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Transcendence":          KHBBSItemData("Magic Command",      code = 227_0010085, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Mini":                   KHBBSItemData("Magic Command",      code = 227_0010086, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Blackout":               KHBBSItemData("Magic Command",      code = 227_0010087, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Ignite":                 KHBBSItemData("Magic Command",      code = 227_0010088, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Confuse":                KHBBSItemData("Magic Command",      code = 227_0010089, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Bind":                   KHBBSItemData("Magic Command",      code = 227_0010090, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Poison":                 KHBBSItemData("Magic Command",      code = 227_0010091, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Slow":                   KHBBSItemData("Magic Command",      code = 227_0010092, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Stop":                   KHBBSItemData("Magic Command",      code = 227_0010093, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Stopra":                 KHBBSItemData("Magic Command",      code = 227_0010094, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Stopga":                 KHBBSItemData("Magic Command",      code = 227_0010095, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Sleep":                  KHBBSItemData("Magic Command",      code = 227_0010096, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Potion":                 KHBBSItemData("Item Command",       code = 227_0010097, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Hi-Potion":              KHBBSItemData("Item Command",       code = 227_0010098, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Mega-Potion":            KHBBSItemData("Item Command",       code = 227_0010099, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Ether":                  KHBBSItemData("Item Command",       code = 227_0010100, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Mega-Ether":             KHBBSItemData("Item Command",       code = 227_0010101, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Panacea":                KHBBSItemData("Item Command",       code = 227_0010102, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Elixir":                 KHBBSItemData("Item Command",       code = 227_0010103, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Megalixir":              KHBBSItemData("Item Command",       code = 227_0010104, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Balloon Letter":         KHBBSItemData("Item Command",       code = 227_0010105, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Vanilla Glitz":          KHBBSItemData("Item Command",       code = 227_0010106, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Fabracadabra":           KHBBSItemData("Item Command",       code = 227_0010107, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Honeybunny":             KHBBSItemData("Item Command",       code = 227_0010108, classification = ItemClassification.filler,      characters = " V "                  ),
    "Bueno Volcano":          KHBBSItemData("Item Command",       code = 227_0010109, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Snow Bear":              KHBBSItemData("Item Command",       code = 227_0010110, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Spark Lemon":            KHBBSItemData("Item Command",       code = 227_0010111, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Goofy Parfait":          KHBBSItemData("Item Command",       code = 227_0010112, classification = ItemClassification.filler,      characters = " V "                  ),
    "Royalberry":             KHBBSItemData("Item Command",       code = 227_0010113, classification = ItemClassification.filler,      characters = "T A"                  ),
    "Sugary Skies":           KHBBSItemData("Item Command",       code = 227_0010114, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Rockin' Crunch":         KHBBSItemData("Item Command",       code = 227_0010115, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Donald Fizz":            KHBBSItemData("Item Command",       code = 227_0010116, classification = ItemClassification.filler,      characters = "  A"                  ),
    "Daisy Sorbet":           KHBBSItemData("Item Command",       code = 227_0010117, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Big Bad Pete":           KHBBSItemData("Item Command",       code = 227_0010118, classification = ItemClassification.filler,      characters = "T  "                  ),
    "Double Crunch":          KHBBSItemData("Item Command",       code = 227_0010119, classification = ItemClassification.filler,      characters = " V "                  ),
    "Group Cure":             KHBBSItemData("Friendship Command", code = 227_0010120, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Group Cura":             KHBBSItemData("Friendship Command", code = 227_0010121, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Group Curaga":           KHBBSItemData("Friendship Command", code = 227_0010122, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Group Esuna":            KHBBSItemData("Friendship Command", code = 227_0010123, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Confetti":               KHBBSItemData("Friendship Command", code = 227_0010124, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Fireworks":              KHBBSItemData("Friendship Command", code = 227_0010125, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Taunt":                  KHBBSItemData("Friendship Command", code = 227_0010126, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Victory Pose":           KHBBSItemData("Friendship Command", code = 227_0010127, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Deck Scramble":          KHBBSItemData("Friendship Command", code = 227_0010128, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Vanish":                 KHBBSItemData("Friendship Command", code = 227_0010129, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Union Rush":             KHBBSItemData("Friendship Command", code = 227_0010130, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Voltage Stack":          KHBBSItemData("Friendship Command", code = 227_0010131, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Trinity Limit":          KHBBSItemData("Friendship Command", code = 227_0010132, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Gold":                   KHBBSItemData("Friendship Command", code = 227_0010133, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Black":                  KHBBSItemData("Friendship Command", code = 227_0010134, classification = ItemClassification.filler,      characters = "TVA"                  ),
   #"Finish":                 KHBBSItemData("Friendship Command", code = 227_0010135, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Wrath of Darkness":      KHBBSItemData("Friendship Command", code = 227_0010136, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Sign of Faith":          KHBBSItemData("Friendship Command", code = 227_0010137, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Wish Circle":            KHBBSItemData("Friendship Command", code = 227_0010138, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Enchanted Step":         KHBBSItemData("Friendship Command", code = 227_0010139, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Wish Shot":              KHBBSItemData("Friendship Command", code = 227_0010140, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Magic Mending":          KHBBSItemData("Friendship Command", code = 227_0010141, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Doc":                    KHBBSItemData("Friendship Command", code = 227_0010142, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Grumpy":                 KHBBSItemData("Friendship Command", code = 227_0010143, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Sneezy":                 KHBBSItemData("Friendship Command", code = 227_0010144, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Happy":                  KHBBSItemData("Friendship Command", code = 227_0010145, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Sleepy":                 KHBBSItemData("Friendship Command", code = 227_0010146, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Bashful":                KHBBSItemData("Friendship Command", code = 227_0010147, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Dopey":                  KHBBSItemData("Friendship Command", code = 227_0010148, classification = ItemClassification.filler,      characters = " VA"                  ),
    "Dark Spiral":            KHBBSItemData("Friendship Command", code = 227_0010149, classification = ItemClassification.filler,      characters = " V "                  ),
    "Dark Splicer":           KHBBSItemData("Friendship Command", code = 227_0010150, classification = ItemClassification.filler,      characters = " V "                  ),
    "Illusion-F":             KHBBSItemData("Friendship Command", code = 227_0010151, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Illusion-L":             KHBBSItemData("Friendship Command", code = 227_0010152, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Illusion-V":             KHBBSItemData("Friendship Command", code = 227_0010153, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Illusion-R":             KHBBSItemData("Friendship Command", code = 227_0010154, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "Illusion-B":             KHBBSItemData("Friendship Command", code = 227_0010155, classification = ItemClassification.filler,      characters = "TVA"                  ),
   #"DUMMY":                  KHBBSItemData("Command",            code = 227_0010156, classification = ItemClassification.filler,      characters = "TVA"                  ),
   #"Slide":                  KHBBSItemData("Movement Command",   code = 227_0010157, classification = ItemClassification.filler,      characters = "T  "                  ),
   #"Jump":                   KHBBSItemData("Movement Command",   code = 227_0010158, classification = ItemClassification.filler,      characters = "TVA"                  ),
    "High Jump":              KHBBSItemData("Movement Command",   code = 227_0010159, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
   #"Dodge Roll":             KHBBSItemData("Movement Command",   code = 227_0010160, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Thunder Roll":           KHBBSItemData("Movement Command",   code = 227_0010161, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
   #"Cartwheel":              KHBBSItemData("Movement Command",   code = 227_0010162, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Firewheel":              KHBBSItemData("Movement Command",   code = 227_0010163, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Air Slide":              KHBBSItemData("Movement Command",   code = 227_0010164, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Ice Slide":              KHBBSItemData("Movement Command",   code = 227_0010165, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Reversal":               KHBBSItemData("Movement Command",   code = 227_0010166, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Glide":                  KHBBSItemData("Movement Command",   code = 227_0010167, classification = ItemClassification.progression, characters = " V ", max_quantity = 1),
    "Superglide":             KHBBSItemData("Movement Command",   code = 227_0010168, classification = ItemClassification.progression, characters = " V ", max_quantity = 1),
    "Fire Glide":             KHBBSItemData("Movement Command",   code = 227_0010169, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Homing Slide":           KHBBSItemData("Movement Command",   code = 227_0010170, classification = ItemClassification.useful,      characters = " VA", max_quantity = 1),
    "Teleport":               KHBBSItemData("Movement Command",   code = 227_0010171, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Sonic Impact":           KHBBSItemData("Movement Command",   code = 227_0010172, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "Double Flight":          KHBBSItemData("Movement Command",   code = 227_0010173, classification = ItemClassification.progression, characters = "  A", max_quantity = 1),
   #"Block":                  KHBBSItemData("Defense Command",    code = 227_0010174, classification = ItemClassification.useful,      characters = "TV ", max_quantity = 1),
    "Renewal Block":          KHBBSItemData("Defense Command",    code = 227_0010175, classification = ItemClassification.useful,      characters = "TV ", max_quantity = 1),
    "Focus Block":            KHBBSItemData("Defense Command",    code = 227_0010176, classification = ItemClassification.useful,      characters = "TV ", max_quantity = 1),
    "Stun Block":             KHBBSItemData("Defense Command",    code = 227_0010177, classification = ItemClassification.useful,      characters = "TV ", max_quantity = 1),
    "Poison Block":           KHBBSItemData("Defense Command",    code = 227_0010178, classification = ItemClassification.useful,      characters = "TV ", max_quantity = 1),
    "Barrier":                KHBBSItemData("Defense Command",    code = 227_0010179, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Renewal Barrier":        KHBBSItemData("Defense Command",    code = 227_0010180, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Focus Barrier":          KHBBSItemData("Defense Command",    code = 227_0010181, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Confuse Barrier":        KHBBSItemData("Defense Command",    code = 227_0010182, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Stop Barrier":           KHBBSItemData("Defense Command",    code = 227_0010183, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Counter Rush":           KHBBSItemData("Reprisal Command",   code = 227_0010184, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Counter Hammer":         KHBBSItemData("Reprisal Command",   code = 227_0010185, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "Reversal Slash":         KHBBSItemData("Reprisal Command",   code = 227_0010186, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Counter Blast":          KHBBSItemData("Reprisal Command",   code = 227_0010187, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Payback Raid":           KHBBSItemData("Reprisal Command",   code = 227_0010188, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Payback Surge":          KHBBSItemData("Reprisal Command",   code = 227_0010189, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Payback Fang":           KHBBSItemData("Reprisal Command",   code = 227_0010190, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "Aerial Recovery":        KHBBSItemData("Reprisal Command",   code = 227_0010191, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
   #"Shotlock":               KHBBSItemData("Shotlock Command",   code = 227_0010192, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Meteor Shower":          KHBBSItemData("Shotlock Command",   code = 227_0010193, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Flame Salvo":            KHBBSItemData("Shotlock Command",   code = 227_0010194, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
   #"Bubble Blaster":         KHBBSItemData("Shotlock Command",   code = 227_0010195, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Dark Volley":            KHBBSItemData("Shotlock Command",   code = 227_0010196, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "Ragnarok":               KHBBSItemData("Shotlock Command",   code = 227_0010197, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Thunderstorm":           KHBBSItemData("Shotlock Command",   code = 227_0010198, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Bio Barrage":            KHBBSItemData("Shotlock Command",   code = 227_0010199, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Prism Rain":             KHBBSItemData("Shotlock Command",   code = 227_0010200, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Pulse Bomb":             KHBBSItemData("Shotlock Command",   code = 227_0010201, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Photon Charge":          KHBBSItemData("Shotlock Command",   code = 227_0010202, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Absolute Zero":          KHBBSItemData("Shotlock Command",   code = 227_0010203, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Lightning Ray":          KHBBSItemData("Shotlock Command",   code = 227_0010204, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
   #"Sonic Shadow":           KHBBSItemData("Shotlock Command",   code = 227_0010205, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "Dark Link":              KHBBSItemData("Shotlock Command",   code = 227_0010206, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Ultima Cannon":          KHBBSItemData("Shotlock Command",   code = 227_0010207, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "Lightbloom":             KHBBSItemData("Shotlock Command",   code = 227_0010208, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Multivortex":            KHBBSItemData("Shotlock Command",   code = 227_0010209, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Critical Impact":        KHBBSItemData("Command Style",      code = 227_0020000, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "Spell Weaver":           KHBBSItemData("Command Style",      code = 227_0020001, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Fever Pitch":            KHBBSItemData("Command Style",      code = 227_0020002, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Firestorm":              KHBBSItemData("Command Style",      code = 227_0020003, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Diamond Dust":           KHBBSItemData("Command Style",      code = 227_0020004, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Thunder Bolt":           KHBBSItemData("Command Style",      code = 227_0020005, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Cyclone":                KHBBSItemData("Command Style",      code = 227_0020006, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Blade Charge":           KHBBSItemData("Command Style",      code = 227_0020007, classification = ItemClassification.useful,      characters = " VA", max_quantity = 1),
    "Sky Climber":            KHBBSItemData("Command Style",      code = 227_0020008, classification = ItemClassification.useful,      characters = " VA", max_quantity = 1),
    "Rock Breaker":           KHBBSItemData("Command Style",      code = 227_0020009, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "Ghost Drive":            KHBBSItemData("Command Style",      code = 227_0020010, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Rhythm Mixer":           KHBBSItemData("Command Style",      code = 227_0020011, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Dark Impulse":           KHBBSItemData("Command Style",      code = 227_0020012, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "Wingblade":              KHBBSItemData("Command Style",      code = 227_0020013, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "Frozen Fortune":         KHBBSItemData("Command Style",      code = 227_0020014, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Treasure Magnet":        KHBBSItemData("Ability",            code = 227_0030000, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 5),
    "HP Prize Plus":          KHBBSItemData("Ability",            code = 227_0030001, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Link Prize Plus":        KHBBSItemData("Ability",            code = 227_0030002, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Lucky Strike":           KHBBSItemData("Ability",            code = 227_0030003, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 5),
    "HP Boost":               KHBBSItemData("Ability",            code = 227_0030004, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Zero EXP":               KHBBSItemData("Ability",            code = 227_0030005, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Fire Boost":             KHBBSItemData("Ability",            code = 227_0030006, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Blizzard Boost":         KHBBSItemData("Ability",            code = 227_0030007, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Thunder Boost":          KHBBSItemData("Ability",            code = 227_0030008, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Cure Boost":             KHBBSItemData("Ability",            code = 227_0030009, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Item Boost":             KHBBSItemData("Ability",            code = 227_0030010, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Attack Haste":           KHBBSItemData("Ability",            code = 227_0030011, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 5),
    "Magic Haste":            KHBBSItemData("Ability",            code = 227_0030012, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 5),
    "Combo F Boost":          KHBBSItemData("Ability",            code = 227_0030013, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 2),
    "Finish Boost":           KHBBSItemData("Ability",            code = 227_0030014, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 2),
    "Combo Plus":             KHBBSItemData("Ability",            code = 227_0030015, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Air Combo Plus":         KHBBSItemData("Ability",            code = 227_0030016, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 3),
    "Fire Screen":            KHBBSItemData("Ability",            code = 227_0030017, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 2),
    "Blizzard Screen":        KHBBSItemData("Ability",            code = 227_0030018, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 2),
    "Thunder Screen":         KHBBSItemData("Ability",            code = 227_0030019, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 2),
    "Dark Screen":            KHBBSItemData("Ability",            code = 227_0030020, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 2),
    "Reload Boost":           KHBBSItemData("Ability",            code = 227_0030021, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Defender":               KHBBSItemData("Ability",            code = 227_0030022, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "EXP Chance":             KHBBSItemData("Ability",            code = 227_0030023, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "EXP Walker":             KHBBSItemData("Ability",            code = 227_0030024, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Damage Syphon":          KHBBSItemData("Ability",            code = 227_0030025, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Second Chance":          KHBBSItemData("Ability",            code = 227_0030026, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Once More":              KHBBSItemData("Ability",            code = 227_0030027, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Scan":                   KHBBSItemData("Ability",            code = 227_0030028, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "Leaf Bracer":            KHBBSItemData("Ability",            code = 227_0030029, classification = ItemClassification.useful,      characters = "TVA", max_quantity = 1),
    "(V) Wayward Wind":       KHBBSItemData("Key Item",           code = 227_0040001, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Treasure Trove":     KHBBSItemData("Key Item",           code = 227_0040002, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Stroke of Midnight": KHBBSItemData("Key Item",           code = 227_0040003, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Fairy Stars":        KHBBSItemData("Key Item",           code = 227_0040004, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Victory Line":       KHBBSItemData("Key Item",           code = 227_0040005, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Mark of a Hero":     KHBBSItemData("Key Item",           code = 227_0040006, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Hyper Drive":        KHBBSItemData("Key Item",           code = 227_0040007, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Pixie Petal":        KHBBSItemData("Key Item",           code = 227_0040008, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Ultima Weapon":      KHBBSItemData("Key Item",           code = 227_0040009, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Sweetstack":         KHBBSItemData("Key Item",           code = 227_0040010, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Frolic Flame":       KHBBSItemData("Key Item",           code = 227_0040011, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Lost Memory":        KHBBSItemData("Key Item",           code = 227_0040012, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Void Gear":          KHBBSItemData("Key Item",           code = 227_0040016, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) No Name":            KHBBSItemData("Key Item",           code = 227_0040017, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(V) Royal Radiance":     KHBBSItemData("Key Item",           code = 227_0040018, classification = ItemClassification.useful,      characters = " V ", max_quantity = 1),
    "(T) Earthshaker":        KHBBSItemData("Key Item",           code = 227_0040256, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Treasure Trove":     KHBBSItemData("Key Item",           code = 227_0040257, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Stroke of Midnight": KHBBSItemData("Key Item",           code = 227_0040258, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Fairy Stars":        KHBBSItemData("Key Item",           code = 227_0040259, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Victory Line":       KHBBSItemData("Key Item",           code = 227_0040260, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Mark of a Hero":     KHBBSItemData("Key Item",           code = 227_0040261, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Hyperdrive":         KHBBSItemData("Key Item",           code = 227_0040262, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Pixie Petal":        KHBBSItemData("Key Item",           code = 227_0040263, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Ultima Weapon":      KHBBSItemData("Key Item",           code = 227_0040264, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Sweetstack":         KHBBSItemData("Key Item",           code = 227_0040265, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Darkgnaw":           KHBBSItemData("Key Item",           code = 227_0040266, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Ends of the Earth":  KHBBSItemData("Key Item",           code = 227_0040267, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Chaos Ripper":       KHBBSItemData("Key Item",           code = 227_0040268, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Void Gear":          KHBBSItemData("Key Item",           code = 227_0040272, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) No Name":            KHBBSItemData("Key Item",           code = 227_0040274, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(T) Royal Radiance":     KHBBSItemData("Key Item",           code = 227_0040275, classification = ItemClassification.useful,      characters = "T  ", max_quantity = 1),
    "(A) Rainfell":           KHBBSItemData("Key Item",           code = 227_0040512, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Treasure Trove":     KHBBSItemData("Key Item",           code = 227_0040513, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Stroke of Midnight": KHBBSItemData("Key Item",           code = 227_0040514, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Fairy Stars":        KHBBSItemData("Key Item",           code = 227_0040515, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Victory Line":       KHBBSItemData("Key Item",           code = 227_0040516, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Mark of a Hero":     KHBBSItemData("Key Item",           code = 227_0040517, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Hyperdrive":         KHBBSItemData("Key Item",           code = 227_0040518, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Pixie Petal":        KHBBSItemData("Key Item",           code = 227_0040519, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Ultima Weapon":      KHBBSItemData("Key Item",           code = 227_0040520, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Sweetstack":         KHBBSItemData("Key Item",           code = 227_0040521, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Destiny's Embrace":  KHBBSItemData("Key Item",           code = 227_0040522, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Stormfall":          KHBBSItemData("Key Item",           code = 227_0040523, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Brightcrest":        KHBBSItemData("Key Item",           code = 227_0040524, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Void Gear":          KHBBSItemData("Key Item",           code = 227_0040528, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) No Name":            KHBBSItemData("Key Item",           code = 227_0040529, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Royal Radiance":     KHBBSItemData("Key Item",           code = 227_0040530, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "(A) Master's Defender":  KHBBSItemData("Key Item",           code = 227_0040531, classification = ItemClassification.useful,      characters = "  A", max_quantity = 1),
    "Wayfinder Ventus":       KHBBSItemData("Key Item",           code = 227_0047964, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Wayfinder Aqua":         KHBBSItemData("Key Item",           code = 227_0047966, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Wayfinder Terra":        KHBBSItemData("Key Item",           code = 227_0047967, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Land of Departure":      KHBBSItemData("World",              code = 227_0050000, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Dwarf Woodlands":        KHBBSItemData("World",              code = 227_0050001, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Castle of Dreams":       KHBBSItemData("World",              code = 227_0050002, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Enchanted Dominion":     KHBBSItemData("World",              code = 227_0050003, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "The Mysterious Tower":   KHBBSItemData("World",              code = 227_0050004, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Radiant Garden":         KHBBSItemData("World",              code = 227_0050005, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Olympus Coliseum":       KHBBSItemData("World",              code = 227_0050006, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Deep Space":             KHBBSItemData("World",              code = 227_0050007, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Destiny Islands":        KHBBSItemData("World",              code = 227_0050008, classification = ItemClassification.progression, characters = "  A", max_quantity = 1),
    "Neverland":              KHBBSItemData("World",              code = 227_0050009, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
    "Disney Town":            KHBBSItemData("World",              code = 227_0050010, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
   #"Keyblade Graveyard":     KHBBSItemData("World",              code = 227_0050011, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
   #"Mirage Arena":           KHBBSItemData("World",              code = 227_0050013, classification = ItemClassification.progression, characters = "TVA", max_quantity = 1),
}

event_item_table: Dict[str, KHBBSItemData] = {}

#Make item categories
item_name_groups: Dict[str, Set[str]] = {}
for item in item_table.keys():
    category = item_table[item].category
    if category not in item_name_groups.keys():
        item_name_groups[category] = set([])
    item_name_groups[category].add(item)